# Generated by Django 5.1.6 on 2025-02-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=50),
        ),
    ]
