# Generated by Django 5.1.6 on 2025-03-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_announcement_id_alter_assignment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_data", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure",
                        to="core.course",
                    ),
                ),
            ],
        ),
    ]
