# Generated by Django 5.1.6 on 2025-03-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_coursestructure"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="assignment_instructions/"
            ),
        ),
    ]
