# Generated by Django 5.1.6 on 2025-03-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addon", "0001_initial"),
        ("core", "0004_assignment_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
